# Generated by Django 4.2.16 on 2024-10-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preciseMed', '0002_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
