# Generated by Django 4.2.16 on 2024-10-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preciseMed', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
