# Generated by Django 4.2.16 on 2024-10-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preciseMed', '0005_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='diagnosisDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
