# Generated by Django 4.2.16 on 2024-10-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preciseMed', '0006_alter_bookings_diagnosisdescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
