# Generated by Django 4.2.16 on 2024-10-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preciseMed', '0010_alter_doctor_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
