# Generated by Django 4.2.16 on 2024-10-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preciseMed', '0011_rename_datetime_booking_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrelationship',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to='preciseMed.patient', unique=True),
        ),
    ]
