# Generated by Django 4.2.16 on 2025-01-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preciseMed', '0014_alter_userrelationship_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='aiPrediction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mriUploaded',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
