# Generated by Django 4.2.16 on 2025-01-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preciseMed', '0015_booking_aiprediction_booking_mriuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mriUploaded',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
